Major release to the main branch
t-bello7/micro-fantasy-nba-league pull request #4
Opened 2022-08-06 15:25 UTC by t-bello7

- create and style home and detailed page section
- create the redux store, action, thunks and reducers for the nba data api
- create the search functionality on the home page
- create unit and integration test

2022-08-06 15:41 UTC, MahmoudBakr23 requested changes
Hello @t-bello7 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Great job working with react routes to set up your app navigation
- Well done working with redux actions, reducers, and store along with react hooks to manipulate the state
- Great job working with the API to fetch the data and store it in the store of your app
- Well done designing your app so far
- Great work adding the search feature
- Nice work with jest and test cases
- Descriptive PR
- Correct Linters
- Well done deploying the app and attaching the live version to the README file
- Nice presentation

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-06 15:41 UTC, MahmoudBakr23 commented on README.md
> --
**Required**
- Please give credit for the author of the original design as dictated in the project requirements

2022-08-06 15:41 UTC, MahmoudBakr23 commented on src/assets/styles/Card.scss
> +.card__container {
**Required**
- Please enhance the design of your app to match the wireframe of the original design. However, the colors are nice.

2022-08-06 15:56 UTC, t-bello7 commented on README.md
> --
Thank you @MahmoudBakr23 . Credits were give to the original design in the Resources Used section of the readme

2022-08-06 15:56 UTC, t-bello7 commented on src/assets/styles/Card.scss
> +.card__container {
Thank you @MahmoudBakr23  for the feedback. The design of my applications follows the design guideline of the original design which is the font style( lato nd Gill ) and the blue color.

2022-08-06 16:29 UTC, Ismailco requested changes
#### Hi @t-bello7, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-06 16:29 UTC, Ismailco commented on README.md
> +- Nelson Ballhead-App-(Free-PSDs) Design
- [ ] Good job adding the credit for the designer as the previous reviewer suggests however Kindly consider adding the correct name of the designer, you can add [Nelson Sakwa](https://www.behance.net/sakwadesignstudio)

2022-08-06 16:29 UTC, Ismailco commented on src/App.jsx
>  const App= () => {
- [ ] I don't get any data from your app so I can't really see what the design looks like, and based on your commits after the first review I see that you changed only the README file, so I will suggest modifying the wireframe as the previous reviewer suggest (I don't know if you have issues with the design but logically you didn't change anything from the last time so I will agree with the last reviewer)

2022-08-06 16:56 UTC, t-bello7 commented on src/App.jsx
>  const App= () => {
Hi @Ismailco Thank you for the review. However you can't run the server locally without creating the authentication keys for the NBA API in the environment variable.

2022-08-08 12:19 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @t-bello7 , 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

Let me point out: 

- [ ] Project is properly deployed, 
- [ ] The project contains a Home page and a Detail page.
- [ ] The project is a single page application
- [ ] Search bar works as expected 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-08 12:53 UTC, t-bello7 commented
😄 Thank you @ShoiraTa  @Ismailco @MahmoudBakr23

2022-08-08 12:53 UTC, merged